### ISSUE TITLE
Presentation on usage of GitHub Actions to run tests in a CI Environment

### ISSUE THREAD

**Issue by igakigongo** [igakigongo/js-battleship#3]

**Comment by ghost** [comment]
It is interesting to use a computer player inherited from the player class.

And I understand that you focus on the logic. However, for the user's experience, ships can be randomly placed, or the user can determine their location.

**Comment by grace-mugoiri** [comment]
This was a good subject as I have never used it before. The actions are actually good place to check your tests etc...

**Comment by igakigongo** [comment]
> It is interesting to use a computer player inherited from the player class.
> 
> And I understand that you focus on the logic. However, for the user's experience, ships can be randomly placed, or the user can determine their location.

Thanks for the feedback Suhyeon, I considered that requirement to be one of the secondary objectives - just like it was stated in the requirements. In due time, I might get back to this project - just to make it more intuitive. 

Thanks once again for the feedback.

**Comment by igakigongo** [comment]
> This was a good subject as I have never used it before. The actions are actually good place to check your tests etc...

Yes, I hope we discover more interesting subjects to discuss. I think Continuous Integration and Deployment is a great topic for Test-Driven Development.

Thank you once again for the great feedback.
